export const Form ={
    fixed_asset_code:"Mã tài sản ",
    fixed_asset_name: "Tên tài sản ",
    fixed_asset_category_code:"Mã loại tài sản ",
    fixed_asset_category_name:"Tên loại tài sản ",
    department_code:"Mã bộ phận sử dụng ",
    department_name:"Tên bộ phận sử dụng ",
    quantity:"Số lượng ",
    cost: "Nguyên giá ",
    life_time:"Năm sử dụng ",
    production_year:"Năm theo dõi ",
    depreciation: "KH/HM lũy kế ",
    depreciation_rate:"Tỷ lệ hao mòn (%) ",
    depreciationTooltip:"Khấu hao/Hao mòn lũy kế ",
    depreciation_value:"Giá trị hao mòn năm ",
    residualValue:"Giá trị còn lại ",
    purchase_date:"Ngày mua ",
    tracked_year:"Ngày bắt đầu sử dụng " ,
    btnSave:"Lưu",
    btnCancel:"Hủy",
    btnClose:"Đóng (ESC)",
   
    

}
export const FormIncrement={
    titleForm:"Thêm chứng từ ghi tăng",
    voucherCode:"Mã chứng từ ",
    startUsedDate:"Ngày bắt đầu sử dụng ",
    incrementDate:"Ngày ghi tăng ",
    note:"Ghi chú ",
    btnSave:"Lưu",
    btnCancel:"Hủy",
    btnClose:"Đóng (ESC)",
    btnChoose:"Chọn tài sản",
    voucher: "Thông tin chứng từ",
    detail: "Thông tin chi tiết",
    placeholderSearch:"Tìm kiếm theo mã, tên tài sản",
    btnAgree:"Đồng ý",
    btnCancelClose:"Hủy bỏ",
    title:"Ghi tăng tài sản",
    horizontalMode: "Giao diện dọc",
    verticalMode:"Giao diện ngang",
    btnAdd:"Thêm"
}