export const URL_Department = "https://localhost:44371/api/Departments";
export const URL_FixedAssetPaging="https://localhost:44371/api/FixedAssets/Filter";
export const URL_Category="https://localhost:44371/api/FixedAssetCategories"
export const URL_FixedAssets="https://localhost:44371/api/FixedAssets"
export const URL_FixedAssetsPut="https://localhost:44371/api/FixedAssets/"
export const URL_GetNewCode="https://localhost:44371/api/FixedAssets/NewCode"
export const URL_DELETE="https://localhost:44371/api/FixedAssets"
export const URL_FixedAssetIncrements="https://localhost:44371/api/FixedAssetIncrements";
export const URL_FixedAssetDetail="https://localhost:44371/api/FixedAssetIncrementDetails"
export const URL_Budget="https://localhost:44371/api/Budgets"
export const URL_GetNewCode_Increment="https://localhost:44371/api/FixedAssetIncrements/NewCode"
